config/routes.rb
Rails.application.routes.draw do
  root   "products#index"
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'
  resources :products
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :image
  validates :name, presence: true
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "正しい画像形式ではありません。" },
                      size:         { less_than: 5.megabytes,
                                      message: "アップロードする画像は5MB以下でなければなりません。" }

  # 表示用のリサイズ済み画像を返す
  def display_image_index
    image[0].variant(resize_to_limit: [220, 220])
  end
end

app/models/user.rb
class User < ApplicationRecord

  # コールバックメソッド ===================================================
  # UserオブジェクトをDBへ保存する前に行う処理
  # emailを小文字に変換する
  before_save { email.downcase! }
  # =====================================================================

  # バリデーション ========================================================
  # 名前 　　　　　検証内容：　存在性、　長さ（最大50文字）
  validates :name,  presence: true, length: { maximum: 50 }

  # メールアドレスの形式を指定する定数（正規表現）
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # メールアドレス　検証内容：　存在性、　長さ（最大255文字）、
  #                        フォーマット(形式)、　一意性(大文字小文字を区別しない)
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # gem BCrypt を導入することで使えるメソッド
  # ハッシュ化したパスワードをDB内のpassword_digestという属性に保存できるようになる
  # モデル内にpassword_digestという属性が含まれていなければこのメソッドは使用できない
  has_secure_password

  # パスワード　　　検証内容：　存在性、　長さ（最小2文字）
  validates :password, presence: true, length: { minimum: 2 }
  # =====================================================================
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_admin_user, only: [:new, :edit, :update, :destroy]
  before_action :correct_admin_user,   only: [:edit]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.image.attach(params[:product][:image])
    if @product.save
      flash[:success] = "新しい商品を登録しました。"
      redirect_to root_url
      # redirect_to product_url(@product)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "商品情報を変更しました。"
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "商品情報を削除しました。"
    redirect_to products_url
  end

  private

    def product_params
      params.require(:product).permit(:name, :price, :stock, :description, :image)
    end

    # 管理者がログイン済みかどうか確認
    def logged_in_admin_user
      unless admin_logged_in?
        flash[:danger] = "運営者アカウントでログインしてください。"
        redirect_to login_url
      end
    end

    # 管理者権限があるかどうか確認
    def correct_admin_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user.admin?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in @user
      flash[:success] = "ログインしました。"
      if @user.admin?
        redirect_to root_url
      else
        redirect_to @user
      end
    else
      flash.now[:danger] = "メールアドレス または パスワードが間違っています。"
      render 'new'
    end
  end

  def destroy
    # ログアウトの処理を書く
    log_out
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録が完了しました。"
      log_in @user
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "退会しました。（ユーザー情報を削除しました）"
    redirect_to root_url
  end


  private

    # Strong_Parameters
    def user_params
      params.require(:user).permit(:name, :email,
                                   :password, :password_confirmation)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # admin権限を持つユーザーがログインしていればtrue、その他ならfalseを返す
  def admin_logged_in?
    if !current_user.nil?
      if current_user.admin?
        return true
      end
    end
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p>©️ Garbage. 2022</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'サンプルアプリ', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %> <!-- ログインしている場合のヘッダーリンク -->
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <% else %>          <!-- ログインしていない場合のヘッダーリンク -->
          <li><%= link_to 'ユーザー登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'progress/text' %>
    </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>商品情報編集</h1>

<!-- Bootstrapを使用して暫定的に見た目を整えているが、ここのフォームはレイアウトを適した形に変更する -->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @product, local: true) do |f| %>
      <%= render 'shared/error_messages_product' %>

      <%= f.label :name, "商品名" %>
      <%= f.text_field :name %>

      <%= f.label :price, "価格" %>
      <%= f.text_field :price %>

      <%= f.label :stock, "在庫数" %>
      <%= f.text_field :stock %>

      <%= f.label :descripion, "商品概要" %>
      <%= f.text_field :description %>

      <%= f.submit "登録", class: "btn btn-primary" %>
      <%= link_to 'キャンセル', root_path, class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% @title = "商品一覧" %>
<h1><%= @title %></h1>

<% if admin_logged_in? %>
  <%= link_to '商品登録', 'products/new' %>
<% end %>

<ul>
  <% @products.each do |product| %>
    <div class="product-item">
      <div class="image">
        <%= image_tag product.display_image_index if product.image.attached? %>
      </div>
      <li>
        <p>商品名：<%= link_to product.name, product %></p>
        <p>価格：<%= product.price  %>円</p>
        <% if admin_logged_in? %>
          <%= link_to '編集', edit_product_path(product) %>
          <%= link_to 'この商品を削除', product, method: :delete, data: { confirm: "この商品を削除します" } %>
        <% end %>
      </li>
    </div>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>商品登録</h1>

<!-- Bootstrapを使用して暫定的に見た目を整えているが、ここのフォームはレイアウトを適した形に変更する -->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @product, local: true) do |f| %>
      <%= render 'shared/error_messages_product' %>

      <%= f.label :name, "商品名" %>
      <%= f.text_field :name %>

      <%= f.label :price, "価格" %>
      <%= f.text_field :price %>

      <%= f.label :stock, "在庫数" %>
      <%= f.text_field :stock %>

      <%= f.label :descripion, "商品概要", class: "description" %>
      <%= f.text_area :description, placeholder: "商品の概要" %>

      <%= f.label :image, "商品画像" %>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

      <%= f.submit "登録", class: "btn btn-primary" %>
      <%= link_to 'キャンセル', root_path, class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %>の詳細ページ</h1>

<span>商品名：</span><%= @product.name %> <br>
<span>価格：</span> <%= @product.price %> <br>
<span>在庫数：</span><%= @product.stock %> <br>
<span>商品概要：</span> <br><%= @product.description %>

<%= link_to "商品一覧", root_url %>
<% if admin_logged_in? %>
  <%= link_to '編集', edit_product_path %>
  <%= link_to 'この商品を削除する', @product , method: :delete,
                                data: { confirm: "本当に削除しますか？" } %>
<% end %>

app/views/progress/_text.html.erb
<div id="progress">
  <h4>★ ユーザーアカウントの初期データ</h4>

  <table border="1">
    <tr><th>アカウント名</th><th>メールアドレス</th><th>パスワード</th><th>管理者権限</th></tr>
    <tr><td>Administrator</td><td>admin@example.com</td><td>footer</td><td>あり</td></tr>
    <tr><td>Test User</td><td>test@example.com</td><td>password</td><td>なし</td></tr>
  </table>

  <h4>★ 認可動作の確認について</h4>
  <h5>★ログインしていない状態</h5>
  <li>・ログインしていない状態で <a href="https://vast-harbor-41701.herokuapp.com/users/1/edit">ユーザーID:1 を編集するページのリンク</a>を踏むと
     ログインページにリダイレクトする。ログインしていなければユーザー編集を行うことはできない。</li>
  <li>・同様に<a href="https://vast-harbor-41701.herokuapp.com/products/1/edit">商品ID:1 を編集するページのリンク</a>を踏んでも同様に
     ログインページにリダイレクトする。</li>

  <h5>★管理者権限なし（Test User）でログインした場合</h5>
  <li><a href="https://vast-harbor-41701.herokuapp.com/products/new">商品ID:1 を登録するページのリンク</a>を踏んでもエラーメッセージとともにログインページにリダイレクトする。管理者権限を持つアカウントでなければ商品の登録・<a href="https://vast-harbor-41701.herokuapp.com/products/1/edit">編集</a>・削除を行うことはできない</li>
</div>

app/views/shared/_error_messages_product.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力されたフォームには<%= pluralize(@product.errors.count, "個のエラーがあります") %>.
    </div>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_user.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力されたフォームには<%= pluralize(@user.errors.count, "個のエラーがあります") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>アカウント情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model:@user, local: true) do |f| %>
      <%= render 'shared/error_messages_user' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "更新" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>アカウント新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages_user' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.email %></p>

<%= link_to 'ユーザー情報を編集する', edit_user_path, class: "btn btn-warning" %>
<%= link_to '退会する（アカウントを削除する）', user_path, method: :delete,
                                           data: { confirm: "アカウントを削除して退会します。よろしいですか？" },
                                           class: "btn btn-danger" %>